apiVersion: v1
kind: Pod
metadata:
  name: db-redis
  labels:
    app: redis
    type: db
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-data
      hostPath:
        # Run mkdir -p ./.data/data/db-redis
        # Run minikube mount ./.data/data/db-redis:/data/redis
        # Sonst nicht persistent!
        path: /data/redis
        type: Directory
