apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: nginx
    type: web
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
