apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
    type: db
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - mountPath: /data
          name: app-data
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: app-pvc
