apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app1
    type: frontend
  annotations:
    version: v1.0.0
    commit: "405531d07718a707026d4fbae543b2d35e04c932"
spec:
  containers:
    - name: app
      image: app:v1.0.0
