apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: nginx
    type: web
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
