apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: nginx
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
