apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: k8s-app
    app.kubernetes.io/version: "2.8.23"
    app.kubernetes.io/component: database
    app.kubernetes.io/created-by: kubectl
spec:
  containers:
    - name: redis
      image: redis:2.8.23
      ports:
        - name: redis
          containerPort: 6379
