apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: k8s-app
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: k8s-app
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: k8s-app
