apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-app
  labels:
    app: rs-nginx
    type: web
spec:
  selector:
    matchLabels:
      app: rs-nginx
      type: web
  replicas: 10
  template:
    metadata:
      labels:
        app: rs-nginx
        type: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 5
