apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-app
  labels:
    app: nginx-rc
    type: web
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-rc
        type: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
