---
- name: Prepare nodes for Longhorn
  hosts: server
  become: yes
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_workshop
  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - bash
        - curl
        - util-linux
        - grep
        - gawk
        - open-iscsi

    - name: Start and enable the iscsid service
      service:
        name: iscsid
        state: started
        enabled: yes
