{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "WordPress.serviceAccountName" . }}
  labels:
{{ include "WordPress.labels" . | indent 4 }}
{{- end -}}
