apiVersion: v1
kind: Service
metadata:
  name: {{ include "WordPress.fullname" . }}-db
  {{- if .Values.namespace -}}
  namespace: {{ .Values.namespace }}
  {{- end}}
  labels:
{{ include "WordPress.labels" . | indent 4 }}
    type: network
    category: service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: db
  selector:
    app.kubernetes.io/name: {{ include "WordPress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    type: db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "WordPress.fullname" . }}-app
  {{- if .Values.namespace -}}
  namespace: {{ .Values.namespace }}
  {{- end}}
  labels:
{{ include "WordPress.labels" . | indent 4 }}
    type: network
    category: service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "WordPress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
