apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: app1
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "app"
      effect: "NoSchedule"
