apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "50"
    required.cpu: "5"
    required.memory: "10Gi"
    limits.cpu: "10"
    limits.memory: "20Gi"
