apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webseite
  namespace: pages
  labels:
    name: webseite
    app: pages
    type: frontend
    category: daemonSet
spec:
  selector:
    matchLabels:
      name: webseite
      app: pages
  template:
    metadata:
      name: webseite
      namespace: pages
      labels:
        name: webseite
        app: pages
        type: frontend
        category: pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2-alpine
          ports:
            - containerPort: 80
              hostPort: 80
