apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: pages
  labels:
    app: pages
    type: network
    category: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: webseite
    app: pages
