apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
    type: web
spec:
  selector:
    matchLabels:
      app: app
      type: web
  replicas: 2
  template:
    metadata:
      name: app
      labels:
        app: app
        type: web
    spec:
        containers:
          - name: app
            image: snic/k8s-app:envs
            ports:
              - containerPort: 5000
            env:
              - name: HOST_PORT
                value: "5000"
              - name: REDIS_HOST
                valueFrom:
                  configMapKeyRef:
                    name: envs
                    key: REDIS_HOST
              - name: REDIS_PORT
                valueFrom:
                  configMapKeyRef:
                    name: envs
                    key: REDIS_HOST
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: secret-envs
                    key: REDIS_PASSWORD
