# Zeigen mit kubectl port-forward pod/db-redis 6380:6379
apiVersion: v1
kind: Pod
metadata:
  name: db-redis
  labels:
    app: redis
    type: db
spec:
  containers:
    - name: redis
      image: bitnami/redis
      ports:
        - containerPort: 6379
      env:
        - name: REDIS_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-envs
              key: REDIS_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-envs
              key: REDIS_PASSWORD
      volumeMounts:
        - mountPath: /bitnami/redis/data
          name: redis-data
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-pvc
