apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: dev
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: k8s-app
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/instance: k8s-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/instance: k8s-app
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: app
          image: snic/k8s-app
          ports:
            - name: k8s-app
              containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis.dbs.svc.cluster.local"
