apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dbs
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: k8s-app
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: database
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - name: redis
          containerPort: 6379
