apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: k8s-app
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: web
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: k8s-app
      nodePort: 30003
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: k8s-app
