apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: nico
data:
    index.html: |
        <html>
        <head>
            <title>Webseite</title>
            <link rel="stylesheet" href="css/app.css">
            <script src="js/app.js"></script>
        </head>
        <body>
            <h1>Webseite</h1>
            <p>Herzlich Willkommen auf der Webseite</p>
        </body>
        </html>

    app.css: |
      html {
          background-color: #ff0000;
          color: #ffffff;
      }
    app.js: |
      setInterval(() => {
        document.body.style.backgroundColor = '#' + Math.floor(Math.random()*16777215).toString(16);
      }, 10);