apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector: # Selektor zum Auffinden der Pods
    app: nginx
