apiVersion: v1
kind: Pod
metadata:
  name: myapp-health
  labels:
    app: health
    type: server
spec:
  containers:
    - name: app
      image: snic/healthcheck
      ports:
        - name: http
          containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health-check
          port: 9090
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health-check
          port: http
        initialDelaySeconds: 5
        periodSeconds: 5
